Question 1

In [ ]:
list = [ x for x in range(2000,3200) if x % 7 == 0 and x % 5 != 0]
print(list)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


Question 2

In [32]:
factorial = lambda x: x and x * factorial(x - 1) or 1
print("Give a number")
x=input()
print(factorial(int(x)))


Give a number
8
40320


Question 3

In [ ]:
n=int(input("Give a number "))
d = dict()

for x in range(1,n+1):
    d[x]=x*x

print(d) 


Input a number 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


Question 4


In [33]:
str=(input("Give a non empty string :"))
n=int(input("Give an integer :"))
front  = str[:n] 
back = str[n+1:]  
print(front + back)
 

Give a non empty string :kitten
Give an integer :1
ktten


Question 5

In [34]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("original array elements:")
print(x)
print("array to list:")
print(x.tolist())




original array elements:
[[0 1]
 [2 3]
 [4 5]]
array to list:
[[0, 1], [2, 3], [4, 5]]


Question 6

In [20]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("Original array1:")
print(x)
print("Original array2:")
print(y)
print("Covariance matrix of the said arrays",np.cov(x, y))


Original array1:
[0 1 2]
Original array2:
[2 1 0]
Covariance matrix of the said arrays [[ 1. -1.]
 [-1.  1.]]


Question 7



In [31]:
import math 
s=[]
function= lambda h : math.sqrt((2*50*h)/30)
print("Enter comma separated integers:")
ch= input()
l=ch.split(",")
for i in l:
  s.append(round(function(int(i))))
print(s)





Enter comma separated integers:
100,150,180
[18, 22, 24]
